alter table DEMOMANGER_CLAZZ add constraint FK_DEMOMANGER_CLAZZ_ON_MAJOR foreign key (MAJOR_ID) references DEMOMANGER_MAJOR(ID);
create index IDX_DEMOMANGER_CLAZZ_ON_MAJOR on DEMOMANGER_CLAZZ (MAJOR_ID);
