alter table DEMOMANGER_STUDENT add constraint FK_DEMOMANGER_STUDENT_ON_MAJOR foreign key (MAJOR_ID) references DEMOMANGER_MAJOR(ID);
create index IDX_DEMOMANGER_STUDENT_ON_MAJOR on DEMOMANGER_STUDENT (MAJOR_ID);
